apiVersion: v1
kind: Service
metadata:
  name: fleetman-position-tracker

spec:

  selector:
    app: position-tracker

  ports:
    - name: http
      port: 8080
      targetPort: 8080

  # Exposed only to other ports in the cluster
  type: ClusterIP
