apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleetman-queue

spec:

  selector:
    matchLabels:
      app: fleetman-queue

  template:
    metadata:
      labels:
        app: fleetman-queue

    spec:
      containers:
        - name: fleetman-queue
          image: richardchesterwood/k8s-fleetman-queue:release2

  # 1 instance should exist at all times.
  replicas: 1
