apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: queue

spec:

  selector:
    matchLabels:
      app: queue

  template:
    metadata:
      labels:
        app: queue

    spec:
      containers:
        - name: queue
          image: richardchesterwood/k8s-fleetman-queue:release1

  # 1 Pod should exist at all times.
  replicas: 1
