apiVersion: v1
kind: Service
metadata:
  name: fleetman-api-gateway

spec:

  selector:
    app: api-gateway

  ports:
    - name: http
      port: 8080
      targetPort: 8080

  # Exposed only to other ports in the cluster
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: fleetman-mongodb

spec:

  selector:
    app: mongodb

  ports:
    - name: mongoport
      port: 27017
      targetPort: 27017

  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: fleetman-position-tracker

spec:

  selector:
    app: position-tracker

  ports:
    - name: http
      port: 8080
      targetPort: 8080

  # Exposed only to other ports in the cluster
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: fleetman-queue

spec:

  selector:
    app: fleetman-queue

  ports:
    # This port is used to expose the admin console
    - name: http
      port: 8161
      targetPort: 8161

    # This port is used to send/receive messages, used internally in the cluster
    - name: endpoint
      port: 61616

  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp

spec:

  selector:
    app: webapp

  ports:
    - name: http
      port: 80
      targetPort: 80

  type: LoadBalancer



