apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: webapp

spec:

  selector:
    matchLabels:
      app: webapp

  template:
    metadata:
      labels:
        app: webapp

    spec:
      containers:
        - name: webapp
          image: richardchesterwood/k8s-fleetman-webapp-angular:release0-5

  # 2 Pod should exist at all times.
  replicas: 2
